id: ID6411A3B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T03:49:03+00:00'
last_modified: '2022-06-08T11:01:53.788403+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1EE39
  title: རྗེ་ཙོང་ཁ་པའི་རྣམ་ཐར།༼སོག་ཡིག༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2BD1:
      image_group_id: I1KG16864
      title: ''
      total_pages: 1044
      order: 1
      base_file: 2BD1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
