id: P009437
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 19:38:47.400213
source_metadata:
  id: bdr:W1EE39
  title: རྗེ་ཙོང་ཁ་པའི་རྣམ་ཐར།༼སོག་ཡིག༽
  author: ''
  volumes:
    6eeabb04ae6844d682b1d60ef9b20ead:
      image_group_id: I1KG16864
      title: ''
      volume_number: 1
      total_pages: 1044
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
